name: Run project tests
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PYTHONDEVMODE: True
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
      - id: python_setup
        uses: actions/setup-python@f38219332975fe8f9c04cca981d674bf22aea1d3 # v2.3.1
        with:
          python-version: '3.10.1'
          architecture: 'x64'
      - id: python_dependencies
        run: |
          pip install pipenv==2021.11.23
      - id: pipenv_cache
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # v2.1.7
        with:
          path: src/.venv
          key: ${{ runner.os }}-${{ steps.python_setup.python-version }}-pipenv-${{ hashFiles('src/Pipfile.lock') }}
          restore-keys: |
            - ${{ runner.os }}-${{ steps.python_setup.python-version }}-pipenv
            - ${{ runner.os }}
      - id: pipenv_install
        if: steps.pipenv_cache.outputs.cache-hit != 'true'
        working-directory: ./src
        env:
          PIPENV_VENV_IN_PROJECT: 1
        run: |
          pipenv install --dev
      - name: BDD tests
        if: ${{ always() }}
        working-directory: ./src
        run: |
          pipenv run coverage run --append --module behave
      - name: Unit tests
        if: ${{ always() }}
        working-directory: ./src
        run: |
          pipenv run coverage run --append --module pytest --junit-xml=test-reports/pytest/junit.xml
      - name: Coverage report
        if: ${{ always() }}
        working-directory: ./src
        run: |
          pipenv run coverage report
          pipenv run coverage xml
      - uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b # v2.1.0
        if: ${{ always() }}
        with:
          files: ./src/coverage.xml # codecov needs the file in XML format
          fail_ci_if_error: true # Fail if CI fails as is important review the delta coverage report
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@dc4b2f22e07d0995dffe65daf902598f695e8827 # v1.25
        if: always()
        with:
          files: src/test-reports/**/*.xml
